### ISSUE TITLE
no header file 'data/scripts/vars/anims.h'

### ISSUE THREAD

**Issue by haxpor** [DCurrent/Fatal-Fury-Chronicles#21]
I got this error `Script error: data/scripts/dc_grapple/config.h, line 8: unable to open file 'data/scripts/vars/anims.h'` and checked that there's no such header file in `data/scripts`.

I noticed comment in `config.h` of dc_grapple mentioning such headers can be found in `bind0010`

```
// From old bind0010
#include "data/scripts/vars/anims.h"
#include "data/scripts/vars/entity.h"
#include "data/scripts/vars/frames.h"
// -From old bind0010
```
Please kindly suggest where can I get these files? Thanks!

**Comment by DCurrent** [comment]
All three of those files were eliminated- they were leftovers from eons ago. Pretty much everything involving this module and the submodules is in progress. You're and anyone else are welcome to them, but I can't make any compatibility or functionality guarantees. :)
